# -*- coding: utf-8 -*-
"""BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Q06PHJWSe_wlsVKkUMG4dRe0WixHhOs
"""

# Microatividade 1
import pandas as pd

dados = pd.read_csv(
    '../dados.csv',
    sep=';',
    engine='python',
    encoding='utf-8'
)

print('Dados Originais')
print(dados)

# Microatividade 2
subconjunto_dados = dados[['Duration', 'Date', 'Calories']]

print('Subconjunto de Dados:')
print(subconjunto_dados)

# Microatividade 3
pd.options.display.max_rows = 9999

print('Dados Originais Completos (com to_string):')
print(dados.to_string())

# Microatividade 4
print('Primeiras 10 linhas do Dataframe:')
print(dados.head(10))

print('Últimas 10 linhas do Dataframe')
print(dados.tail(10))

# Microatividade 5
print('Informações Gerais:')
print(dados.info())

print('Dimensões do Dataframe:')
print(f'Número de linhas: {dados.shape[0]}')
print(f'Número de colunas: {dados.shape[1]}')

print('Número de valores nulos:')
print(dados.isnull().sum())

print('Tipos de Dados:')
print(dados.dtypes)

print('Memória ultilizada:')
print(dados.memory_usage())
print(f'Memória total usada: {dados.memory_usage().sum() / 1024:2f} KB')