# -*- coding: utf-8 -*-
"""BigData_trabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weMBes_l7MK_Bx8SgYWWZbPeaIp-sTwA
"""

import pandas as pd

# Lendo e tratando dados
df = pd.read_csv(
    './dados.csv',
    sep=';',
    engine='python',
    encoding='utf-8'
)

# Mostrando dataframe orignal
print("Dados Originais:")
print(df)

# Mostrando informações gerais sobre o dataframe
print("Informações Gerais:")
print(df.info())

# Apresentando primeiras 10 linhas
print("Primeiras dez linhas:")
print(df.head(10))

# Apresentando últimas 10 linhas
print("Últimas dez linhas:")
print(df.tail(10))

# Fazendo uma cópia do dataframe original
dfCopia = df

# Trocando valores nulos por 0 na coluna 'Calories'
dfCopia['Calories'] = dfCopia['Calories'].fillna(0)
print("Dados com a coluna Calories corrigida")
print(dfCopia)

# Trocando valores nulos por 1900/01/01 na coluna 'Date'
dfCopia['Date'] = dfCopia['Date'].fillna('1900/01/01')
print("Correção de datas nulas")
print(dfCopia)

# Tratando 2 erros
# Primeiro erro: proposital para testes, trocando 1900/01/01 por NaT (também conhecido como nulo)
dfCopia['Date'] = dfCopia['Date'].replace('1900/01/01', pd.NaT)

# Segundo erro: Data em formato de string sem separações, trocando valor original por valor corrigido manualmente (20201226 para 2020/12/26)
dfCopia['Date'] = dfCopia['Date'].replace('20201226', pd.to_datetime('2020/12/26'))

# Formatando toda a coluna Date para formato em data
dfCopia['Date'] = pd.to_datetime(dfCopia['Date'])

print("Dataframe corrigido:")
print(dfCopia)

# Removendo do dataframe qualquer data que tenha valor nulo.
dfCopia = dfCopia.dropna(subset=['Date'])
print("Dataframe final:")
print(dfCopia)